package edu.unm.registration.model;

// Generated Apr 20, 2015 4:55:56 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VknsSpriden generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="VKNS_SPRIDEN")
public class VknsSpriden implements java.io.Serializable {
	@Id
	@Column(name = "SPRIDEN_ID")
	private String spridenId;
	
	@Column(name = "SPRIDEN_PIDM")
	private int spridenPidm;
	
	@Column(name = "SPRIDEN_LAST_NAME")
	private String spridenLastName;
	
	@Column(name = "SPRIDEN_FIRST_NAME")
	private String spridenFirstName;
	
	@Column(name = "SPRIDEN_MI")
	private String spridenMi;
	
	@Column(name = "SPRIDEN_CHANGE_IND")
	private String spridenChangeInd;
	
	@Column(name = "SPRIDEN_ENTITY_IND")
	private String spridenEntityInd;
	
	@Column(name = "SPRIDEN_ACTIVITY_DATE")
	private Date spridenActivityDate;
	
	@Column(name = "SPRIDEN_USER")
	private String spridenUser;
	
	@Column(name = "SPRIDEN_ORIGIN")
	private String spridenOrigin;
	
	@Column(name = "SPRIDEN_SEARCH_LAST_NAME")
	private String spridenSearchLastName;
	
	@Column(name = "SPRIDEN_SEARCH_FIRST_NAME")
	private String spridenSearchFirstName;
	
	@Column(name = "SPRIDEN_SEARCH_MI")
	private String spridenSearchMi;
	
	@Column(name = "SPRIDEN_SOUNDEX_LAST_NAME")
	private String spridenSoundexLastName;
	
	@Column(name = "SPRIDEN_SOUNDEX_FIRST_NAME")
	private String spridenSoundexFirstName;
	
	@Column(name = "SPRIDEN_NTYP_CODE")
	private String spridenNtypCode;
	
	@Column(name = "SPRIDEN_CREATE_USER")
	private String spridenCreateUser;
	
	@Column(name = "SPRIDEN_CREATE_DATE")
	private Date spridenCreateDate;
	
	@Column(name = "SPRIDEN_DATA_ORIGIN")
	private String spridenDataOrigin;
	
	@Column(name = "SPRIDEN_CREATE_FDMN_CODE")
	private String spridenCreateFdmnCode;
	
	@Column(name = "SPRIDEN_NAME_ERROR_CODE")
	private String spridenNameErrorCode;
	
	@Column(name = "SPRIDEN_SURNAME_PREFIX")
	private String spridenSurnamePrefix;
	
	@Column(name = "SPRIDEN_SURROGATE_ID")
	private BigDecimal spridenSurrogateId;
	
	@Column(name = "SPRIDEN_VERSION")
	private BigDecimal spridenVersion;
	
	@Column(name = "SPRIDEN_USER_ID")
	private String spridenUserId;
	
	@Column(name = "SPRIDEN_VPDI_CODE")
	private String spridenVpdiCode;

	public VknsSpriden() {
	}

	public VknsSpriden(String spridenId, int spridenPidm,
			String spridenLastName, Date spridenActivityDate) {
		this.spridenId = spridenId;
		this.spridenPidm = spridenPidm;
		this.spridenLastName = spridenLastName;
		this.spridenActivityDate = spridenActivityDate;
	}

	public VknsSpriden(String spridenId, int spridenPidm,
			String spridenLastName, String spridenFirstName, String spridenMi,
			String spridenChangeInd, String spridenEntityInd,
			Date spridenActivityDate, String spridenUser, String spridenOrigin,
			String spridenSearchLastName, String spridenSearchFirstName,
			String spridenSearchMi, String spridenSoundexLastName,
			String spridenSoundexFirstName, String spridenNtypCode,
			String spridenCreateUser, Date spridenCreateDate,
			String spridenDataOrigin, String spridenCreateFdmnCode,
			String spridenNameErrorCode, String spridenSurnamePrefix,
			BigDecimal spridenSurrogateId, BigDecimal spridenVersion,
			String spridenUserId, String spridenVpdiCode) {
		this.spridenId = spridenId;
		this.spridenPidm = spridenPidm;
		this.spridenLastName = spridenLastName;
		this.spridenFirstName = spridenFirstName;
		this.spridenMi = spridenMi;
		this.spridenChangeInd = spridenChangeInd;
		this.spridenEntityInd = spridenEntityInd;
		this.spridenActivityDate = spridenActivityDate;
		this.spridenUser = spridenUser;
		this.spridenOrigin = spridenOrigin;
		this.spridenSearchLastName = spridenSearchLastName;
		this.spridenSearchFirstName = spridenSearchFirstName;
		this.spridenSearchMi = spridenSearchMi;
		this.spridenSoundexLastName = spridenSoundexLastName;
		this.spridenSoundexFirstName = spridenSoundexFirstName;
		this.spridenNtypCode = spridenNtypCode;
		this.spridenCreateUser = spridenCreateUser;
		this.spridenCreateDate = spridenCreateDate;
		this.spridenDataOrigin = spridenDataOrigin;
		this.spridenCreateFdmnCode = spridenCreateFdmnCode;
		this.spridenNameErrorCode = spridenNameErrorCode;
		this.spridenSurnamePrefix = spridenSurnamePrefix;
		this.spridenSurrogateId = spridenSurrogateId;
		this.spridenVersion = spridenVersion;
		this.spridenUserId = spridenUserId;
		this.spridenVpdiCode = spridenVpdiCode;
	}

	public String getSpridenId() {
		return this.spridenId;
	}

	public void setSpridenId(String spridenId) {
		this.spridenId = spridenId;
	}

	public int getSpridenPidm() {
		return this.spridenPidm;
	}

	public void setSpridenPidm(int spridenPidm) {
		this.spridenPidm = spridenPidm;
	}

	public String getSpridenLastName() {
		return this.spridenLastName;
	}

	public void setSpridenLastName(String spridenLastName) {
		this.spridenLastName = spridenLastName;
	}

	public String getSpridenFirstName() {
		return this.spridenFirstName;
	}

	public void setSpridenFirstName(String spridenFirstName) {
		this.spridenFirstName = spridenFirstName;
	}

	public String getSpridenMi() {
		return this.spridenMi;
	}

	public void setSpridenMi(String spridenMi) {
		this.spridenMi = spridenMi;
	}

	public String getSpridenChangeInd() {
		return this.spridenChangeInd;
	}

	public void setSpridenChangeInd(String spridenChangeInd) {
		this.spridenChangeInd = spridenChangeInd;
	}

	public String getSpridenEntityInd() {
		return this.spridenEntityInd;
	}

	public void setSpridenEntityInd(String spridenEntityInd) {
		this.spridenEntityInd = spridenEntityInd;
	}

	public Date getSpridenActivityDate() {
		return this.spridenActivityDate;
	}

	public void setSpridenActivityDate(Date spridenActivityDate) {
		this.spridenActivityDate = spridenActivityDate;
	}

	public String getSpridenUser() {
		return this.spridenUser;
	}

	public void setSpridenUser(String spridenUser) {
		this.spridenUser = spridenUser;
	}

	public String getSpridenOrigin() {
		return this.spridenOrigin;
	}

	public void setSpridenOrigin(String spridenOrigin) {
		this.spridenOrigin = spridenOrigin;
	}

	public String getSpridenSearchLastName() {
		return this.spridenSearchLastName;
	}

	public void setSpridenSearchLastName(String spridenSearchLastName) {
		this.spridenSearchLastName = spridenSearchLastName;
	}

	public String getSpridenSearchFirstName() {
		return this.spridenSearchFirstName;
	}

	public void setSpridenSearchFirstName(String spridenSearchFirstName) {
		this.spridenSearchFirstName = spridenSearchFirstName;
	}

	public String getSpridenSearchMi() {
		return this.spridenSearchMi;
	}

	public void setSpridenSearchMi(String spridenSearchMi) {
		this.spridenSearchMi = spridenSearchMi;
	}

	public String getSpridenSoundexLastName() {
		return this.spridenSoundexLastName;
	}

	public void setSpridenSoundexLastName(String spridenSoundexLastName) {
		this.spridenSoundexLastName = spridenSoundexLastName;
	}

	public String getSpridenSoundexFirstName() {
		return this.spridenSoundexFirstName;
	}

	public void setSpridenSoundexFirstName(String spridenSoundexFirstName) {
		this.spridenSoundexFirstName = spridenSoundexFirstName;
	}

	public String getSpridenNtypCode() {
		return this.spridenNtypCode;
	}

	public void setSpridenNtypCode(String spridenNtypCode) {
		this.spridenNtypCode = spridenNtypCode;
	}

	public String getSpridenCreateUser() {
		return this.spridenCreateUser;
	}

	public void setSpridenCreateUser(String spridenCreateUser) {
		this.spridenCreateUser = spridenCreateUser;
	}

	public Date getSpridenCreateDate() {
		return this.spridenCreateDate;
	}

	public void setSpridenCreateDate(Date spridenCreateDate) {
		this.spridenCreateDate = spridenCreateDate;
	}

	public String getSpridenDataOrigin() {
		return this.spridenDataOrigin;
	}

	public void setSpridenDataOrigin(String spridenDataOrigin) {
		this.spridenDataOrigin = spridenDataOrigin;
	}

	public String getSpridenCreateFdmnCode() {
		return this.spridenCreateFdmnCode;
	}

	public void setSpridenCreateFdmnCode(String spridenCreateFdmnCode) {
		this.spridenCreateFdmnCode = spridenCreateFdmnCode;
	}

	public String getSpridenNameErrorCode() {
		return this.spridenNameErrorCode;
	}

	public void setSpridenNameErrorCode(String spridenNameErrorCode) {
		this.spridenNameErrorCode = spridenNameErrorCode;
	}

	public String getSpridenSurnamePrefix() {
		return this.spridenSurnamePrefix;
	}

	public void setSpridenSurnamePrefix(String spridenSurnamePrefix) {
		this.spridenSurnamePrefix = spridenSurnamePrefix;
	}

	public BigDecimal getSpridenSurrogateId() {
		return this.spridenSurrogateId;
	}

	public void setSpridenSurrogateId(BigDecimal spridenSurrogateId) {
		this.spridenSurrogateId = spridenSurrogateId;
	}

	public BigDecimal getSpridenVersion() {
		return this.spridenVersion;
	}

	public void setSpridenVersion(BigDecimal spridenVersion) {
		this.spridenVersion = spridenVersion;
	}

	public String getSpridenUserId() {
		return this.spridenUserId;
	}

	public void setSpridenUserId(String spridenUserId) {
		this.spridenUserId = spridenUserId;
	}

	public String getSpridenVpdiCode() {
		return this.spridenVpdiCode;
	}

	public void setSpridenVpdiCode(String spridenVpdiCode) {
		this.spridenVpdiCode = spridenVpdiCode;
	}

}
